import z from 'zod';

export const DemoSchema: z.ZodType<any> = z.object({
  test01: z.string(),
  test02: z.number(),
  test03: z.boolean(),
  test04: z.string().optional(),
  test05: z.coerce.string(),
  test06: z.coerce.number(),
  test07: z.coerce.boolean(),
  test08: z.string().max(5),
  test09: z.string().min(5),
  test10: z.string().length(5),
  test11: z.string().regex(/^[a-z]+$/),
  test12: z.string().startsWith('aaa'),
  test13: z.string().endsWith('zzz'),
  test14: z.string().includes('---'),
  test15: z.string().uppercase(),
  test16: z.string().lowercase(),
  test17: z.email(),
  test18: z.uuid(),
  test19: z.url(),
  test20: z.jwt(),
  test21: z.ipv4(),
  test22: z.ipv6(),
  test23: z.iso.date(),
  test24: z.iso.time(),
  test25: z.iso.datetime(),
  test26: z.iso.duration(),
  test27: z.number().gt(5),
  test28: z.number().gte(5),
  test29: z.number().lt(5),
  test30: z.number().lte(5),
  test31: z.number().positive(),
  test32: z.number().nonnegative(),
  test33: z.number().negative(),
  test34: z.number().nonpositive(),
  test35: z.number().multipleOf(5),
  test36: z.int(),
  test37: z.int32(),
  test38: z.date().min(new Date('1900-01-01'), { error: 'Too old!' }),
  test39: z.date().max(new Date(), { error: 'Too young!' }),
  test40: z.enum(['Salmon', 'Tuna', 'Trout']),
  test41: z.array(z.string()).min(5),
  test42: z.array(z.string()).max(5),
  test43: z.array(z.string()).length(5),
});
